name: pet_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0+4
  flutter_dotenv: ^2.1.0

  # redux denpendencies
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  redux_thunk: ^0.3.0
  
  shared_preferences: ^0.5.6+3
  json_serializable: '>=3.2.5'
  google_fonts: ^0.3.5
  cached_network_image: ^2.0.0
  
  # petshop dependencies
  introduction_screen: ^1.0.8
  flutter_svg: ^0.17.1
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  wc_flutter_share: ^0.2.0
  provider:
  bubble_tab_indicator: ^0.1.4
  carousel_slider: ^2.0.0
  permission_handler: ^3.1.0
  geolocator: ^5.3.2+2
  geolocation: ^1.1.2
  mask_text_input_formatter: ^1.0.7
  dio: ^3.0.9
  geocoder: ^0.2.1
  location: ^3.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  
  # for responsiveness of the app for different screen types
  responsive_builder: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  
  flutter_redux_dev_tools: ^0.4.0
  redux_dev_tools: ^0.5.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/cardImages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
