# Made by Vanam Hemanth

name: Build backend NODEJS app and test

on: 
  pull_request:
    branches: 
      - master


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up NODEJS version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'  
      
    - name: install all dependencies, build and test
      run: |
        cd Backend/
        npm ci
        npm run build --if-present
        npm run test --if-present